apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  type: ClusterIP
  selector:
    app: backend-mail
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mail
  template:
    metadata:
      labels:
        app: backend-mail
    spec:
      containers:
        - name: backend-mail
          image: swayamjain/chat-app-mail:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "admin"
            - name: RABBITMQ_PASSWORD
              value: "password123"
            - name: EMAIL_USER
              value: "swarag6900@gmail.com"
            - name: EMAIL_PASSWORD
              value: "lvlngokqoztxjddb"
